version: '3'
services:
  mongo:
    image: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin 
      - MONGO_INITDB_ROOT_PASSWORD=123456 
      - MONGO_INITDB_DATABASE=db_js 
    ports:
      - 27017
    networks:
      - api
# cassandra:
#    image: cassandra:3.0.29
#    hostname: cassandra
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=mongoadmin 
#      - MONGO_INITDB_ROOT_PASSWORD=123456 
#      - MONGO_INITDB_DATABASE=db_js 
#    ports:
#      - 7000
#    networks:
#      - api
  node:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - NODE_ENV=prod
    ports:
      - 3000
    networks:
      - api
networks:
  api:
    driver: bridge  
